name: bashtest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Run bash tests
        run: |
          set -x # verbose-mode

          python -m pip install --upgrade pip
          pip3 install -e .
          pip3 install -r requirements.txt

          git_root="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
          echo "git_root: $git_root"

          pushd $git_root >/dev/null
          git clone https://github.com/kamangir/awesome-bash-cli.git
          cd awesome-bash-cli
          pip3 install -e .
          pip3 install -r requirements.txt
          popd >/dev/null

          source $git_root/awesome-bash-cli/bash/abcli.sh ~terraform

          giza test