name: bashtest

on: [push]

jobs:
  bashtest:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, 'no-workflow')"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r requirements.txt
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1
      - name: Install LaTeX, ps2pdf, and csquotes
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive texlive-latex-extra texlive-bibtex-extra texlive-fonts-recommended
          sudo apt-get install -y texlive-humanities  # This package includes csquotes
          sudo apt-get install -y ghostscript
      - name: Run bash tests
        run: |
          ./.github/workflows/bashtest.sh giza
